export enum ReturnTicketStatus {
    PENDING = 'PENDING',
    CANCEL = 'CANCELED',
    REJECTED = 'REJECTED',
    IN_PROGRESS = 'IN_PROGRESS',
    // APPROVED = 'APPROVED',
    DELIVERING = 'DELIVERING',
    RETURNED = 'RETURNED',
    FAIL_RETURNED = 'FAIL_RETURNED',
    REFUNDED = 'REFUNDED'
}
